services:
  node-red:
    image: nodered/node-red:latest
    container_name: nodered
    restart: unless-stopped
    ports:
      - "1880:1880"
    volumes:
      - node_red_data:/data

volumes:
  node_red_data: